### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Timeslides** [steve228uk/TunnelDeck#10]
Plugin is not working at all since one of the latest Steam Deck updates on the Beta branch.

**Comment by dtantono** [comment]
I second this. I updated the SteamOS to latest stable version and I tried uninstalled and reinstalled the plugin. But, I got VPN Connection and the menu does not show up. 
![Screenshot_20230225_234733](https://user-images.githubusercontent.com/29157187/225499269-3486c35b-4058-45ed-858c-c1128c52a5bb.png)

**Comment by hateinternet** [comment]
hi, i have same problem

**Comment by MNarath1** [comment]
> Hi,
> 
> Same here.
> 
> Controller Tools seems to have the same issue. So I would guess this is an issue with decky itself.
> 
> 
> 
> Running OS version 3.4.6
> 
> Build: 20230313.1
> 
> Kernel: 5.13.0-valve36-1-neptune
> 
> Steam Version: 1678914933
> 
> 
> 
> Edit:
> 
> See here: [https://github.com/SteamDeckHomebrew/decky-loader/issues/396](url)
> 
> 

It seems to be the former beta version (now stable) has some changes to the ui that don't work together well with tunneldeck this probably cannot be fixed without an update to the tunneldeck plugin itself

**Comment by MNarath1** [comment]
> Having the same problem. Does it has a fix?

For now i fixed it for myself by updating the frontend dependancy to the latest version and manually building the plugin then transfering it to the steam deck works fine still ovpn trough sysext is still broken trough so still had to manually install that with pacman

**Comment by borland12** [comment]
> > Having the same problem. Does it has a fix?
> 
> For now i fixed it for myself by updating the frontend dependancy to the latest version and manually building the plugin then transfering it to the steam deck works fine still ovpn trough sysext is still broken trough so still had to manually install that with pacman

Hi, will you be able to create a short guide to do the steps you have described? 
I'm not a tech person, though need this plugin to continue using my Deck :(

**Comment by NL-TCH** [comment]
fix for now:
1. go to the deckloader menu
2. go to the settings menu (gear icon) in the top right
3. set the 'Plugin Store Channel' to testing
4. go to plugins and update the tunneldeck plugin to the testing version (1.0.2-efbc4cc)

now it should work again

**Comment by jeav123** [comment]
> 

Thank you. Its working now.

**Comment by steve228uk** [comment]
This should be fixed in the version now available on the Decky store.
