### ISSUE TITLE
OVPN connections cannot be activated from Tunnel Deck Plugin in Gaming Mode.

### ISSUE THREAD

**Issue by Mcmeman** [steve228uk/TunnelDeck#17]
Steam OS Channel: Stable
Steam OS Version: 3.4.10
Steam OS Build: 20230831.1
Decky Version: 2.10.4
Tunnel Deck Version: 1.0.2-1

Expected Behavior:
Tunnel Deck toggles enable and disable OVPN connections added in Desktop Mode.

Observed Behavior:
Tunnel deck can see the connections but cannot activate them, enabling the toggle will see the toggle move to the on position but the VPN Connection never connects.

Troubleshooting:
Connections can be successfully enabled when enabled from Desktop Mode and the connection persists when switching back to gaming mode. Tunnel deck can then kill the connection but cannot re-establish. In this state moving to and from Desktop mode is required to enable the connection.

**Comment by Bro-11** [comment]
Same, doesn't work for ProtonVPN connections. (They use OpenVPN)

**Comment by padlax** [comment]
The same thing as the author have whitten.

**Comment by OmikroN-TNS** [comment]
Setting this up in the VPN configuration panel did the trick for me:

![image](https://github.com/steve228uk/TunnelDeck/assets/89336657/a5c5df82-01df-4f09-97c3-d6d8963f6f21)

**Comment by Mcmeman** [comment]
> Setting this up in the VPN configuration panel did the trick for me:
> 
> ![image](https://user-images.githubusercontent.com/89336657/272043443-a5c5df82-01df-4f09-97c3-d6d8963f6f21.png)

Odd that did work for me but the setting was already set, but upon re-applying it worked.

**Comment by Mcmeman** [comment]
Can be corrected by ensuring that the non-encrypted password settings for all users are applied/re-applied.
