### ISSUE TITLE
Changes to archlinux-mirror breaks installation

### ISSUE THREAD

**Issue by mineinmonkey** [steve228uk/TunnelDeck#4]
The install script for OpenVPN plugin for NetworkManager trys to install a package from archlinux-mirror/extra but I think this directory was renamed to extra-3.3 so the networkmanager-openvpn.raw file is empty when it's made.

**Comment by mineinmonkey** [comment]
After changing the URL in the openvpn.list file, the install script correctly installs the package so I'm pretty sure that's what it is.

**Comment by rpigab** [comment]
Can confirm it works! Thank you very much.

**Comment by steve228uk** [comment]
@mineinmonkey Thanks for reporting and apologies for the delay in getting back to you. I've been unwell so only just been able to pick this up but a fix has been submitted. https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/195
